FROM openviking-openvino-base:2026.3
WORKDIR /srv/openviking-openvino
COPY embedding_config.py /srv/openviking-openvino/config.py
COPY embedding_main.py /srv/openviking-openvino/main.py
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
